### ISSUE TITLE
`pip freeze` from `conda` environment into requirements.txt produces `@ file://` entries 

### ISSUE THREAD

**Issue by joshuacwnewton** [oscarpimentel/sne-lightcurves-synthetic#1]
Just giving you a quick heads-up that your project might be affected by https://github.com/conda/conda/issues/11580, since your newly-created `requirements.txt` file contains many `file @` entries:

https://github.com/oscarpimentel/sne-lightcurves-synthetic/blob/5c7111ee2c2e49346e16896d034577a64da46225/requirements.txt#L1-L112

Note: I found your project through a GitHub search:

> Also, a quick GitHub-wide search for `certifi_1655968806487` returns my issue ([spinalcordtoolbox/spinalcordtoolbox#3817](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3817)) and only 1 other result: [oscarpimentel/sne-lightcurves-synthetic@`f44c98c`/requirements.txt](https://github.com/oscarpimentel/sne-lightcurves-synthetic/blob/f44c98c6e7e11407c002e688c3f82bcd1538b0a2/requirements.txt) (June 24th, 2022)

I hope this saves some headache. :)

**Comment by oscarpimentel** [comment]
Thank you! this actually helped me!
